# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openshift_assisted_service
from openshift_assisted_service.models.list_versions import ListVersions  # noqa: E501
from openshift_assisted_service.rest import ApiException

class TestListVersions(unittest.TestCase):
    """ListVersions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ListVersions
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListVersions`
        """
        model = openshift_assisted_service.models.list_versions.ListVersions()  # noqa: E501
        if include_optional :
            return ListVersions(
                versions = {
                    'key' : ''
                    }, 
                release_tag = ''
            )
        else :
            return ListVersions(
        )
        """

    def testListVersions(self):
        """Test ListVersions"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
