# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openshift_assisted_service
from openshift_assisted_service.models.image_info import ImageInfo  # noqa: E501
from openshift_assisted_service.rest import ApiException

class TestImageInfo(unittest.TestCase):
    """ImageInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ImageInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageInfo`
        """
        model = openshift_assisted_service.models.image_info.ImageInfo()  # noqa: E501
        if include_optional :
            return ImageInfo(
                ssh_public_key = '', 
                size_bytes = 0, 
                download_url = '', 
                generator_version = '', 
                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                expires_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                static_network_config = '', 
                type = 'full-iso'
            )
        else :
            return ImageInfo(
        )
        """

    def testImageInfo(self):
        """Test ImageInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
