# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openshift_assisted_service
from openshift_assisted_service.models.architecture_support_level_id import ArchitectureSupportLevelId  # noqa: E501
from openshift_assisted_service.rest import ApiException

class TestArchitectureSupportLevelId(unittest.TestCase):
    """ArchitectureSupportLevelId unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArchitectureSupportLevelId(self):
        """Test ArchitectureSupportLevelId"""
        # inst = ArchitectureSupportLevelId()

if __name__ == '__main__':
    unittest.main()
