# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openshift_assisted_service
from openshift_assisted_service.models.host_role_update_params import HostRoleUpdateParams  # noqa: E501
from openshift_assisted_service.rest import ApiException

class TestHostRoleUpdateParams(unittest.TestCase):
    """HostRoleUpdateParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHostRoleUpdateParams(self):
        """Test HostRoleUpdateParams"""
        # inst = HostRoleUpdateParams()

if __name__ == '__main__':
    unittest.main()
