# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openshift_assisted_service
from openshift_assisted_service.models.steps import Steps  # noqa: E501
from openshift_assisted_service.rest import ApiException

class TestSteps(unittest.TestCase):
    """Steps unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Steps
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Steps`
        """
        model = openshift_assisted_service.models.steps.Steps()  # noqa: E501
        if include_optional :
            return Steps(
                next_instruction_seconds = 56, 
                post_step_action = 'continue', 
                instructions = [
                    openshift_assisted_service.models.step.step(
                        step_type = 'connectivity-check', 
                        step_id = '', 
                        args = [
                            ''
                            ], )
                    ]
            )
        else :
            return Steps(
        )
        """

    def testSteps(self):
        """Test Steps"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
