# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openshift_assisted_service
from openshift_assisted_service.models.host_registration_response_all_of_next_step_runner_command import HostRegistrationResponseAllOfNextStepRunnerCommand  # noqa: E501
from openshift_assisted_service.rest import ApiException

class TestHostRegistrationResponseAllOfNextStepRunnerCommand(unittest.TestCase):
    """HostRegistrationResponseAllOfNextStepRunnerCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test HostRegistrationResponseAllOfNextStepRunnerCommand
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `HostRegistrationResponseAllOfNextStepRunnerCommand`
        """
        model = openshift_assisted_service.models.host_registration_response_all_of_next_step_runner_command.HostRegistrationResponseAllOfNextStepRunnerCommand()  # noqa: E501
        if include_optional :
            return HostRegistrationResponseAllOfNextStepRunnerCommand(
                command = '', 
                args = [
                    ''
                    ], 
                retry_seconds = 56
            )
        else :
            return HostRegistrationResponseAllOfNextStepRunnerCommand(
        )
        """

    def testHostRegistrationResponseAllOfNextStepRunnerCommand(self):
        """Test HostRegistrationResponseAllOfNextStepRunnerCommand"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
