# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openshift_assisted_service
from openshift_assisted_service.models.cluster_progress_info import ClusterProgressInfo  # noqa: E501
from openshift_assisted_service.rest import ApiException

class TestClusterProgressInfo(unittest.TestCase):
    """ClusterProgressInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ClusterProgressInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ClusterProgressInfo`
        """
        model = openshift_assisted_service.models.cluster_progress_info.ClusterProgressInfo()  # noqa: E501
        if include_optional :
            return ClusterProgressInfo(
                total_percentage = 56, 
                preparing_for_installation_stage_percentage = 56, 
                installing_stage_percentage = 56, 
                finalizing_stage_percentage = 56
            )
        else :
            return ClusterProgressInfo(
        )
        """

    def testClusterProgressInfo(self):
        """Test ClusterProgressInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
