# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openshift_assisted_service
from openshift_assisted_service.models.disk import Disk  # noqa: E501
from openshift_assisted_service.rest import ApiException

class TestDisk(unittest.TestCase):
    """Disk unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Disk
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Disk`
        """
        model = openshift_assisted_service.models.disk.Disk()  # noqa: E501
        if include_optional :
            return Disk(
                id = '', 
                drive_type = 'Unknown', 
                has_uuid = True, 
                vendor = '', 
                name = '', 
                path = '', 
                hctl = '', 
                by_path = '', 
                by_id = '', 
                model = '', 
                wwn = '', 
                serial = '', 
                size_bytes = 56, 
                bootable = True, 
                removable = True, 
                is_installation_media = True, 
                installation_eligibility = openshift_assisted_service.models.disk_installation_eligibility.disk_installation_eligibility(
                    eligible = True, 
                    not_eligible_reasons = [
                        ''
                        ], ), 
                smart = '', 
                io_perf = openshift_assisted_service.models.io_perf.io_perf(
                    sync_duration = 56, ), 
                holders = ''
            )
        else :
            return Disk(
        )
        """

    def testDisk(self):
        """Test Disk"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
