# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openshift_assisted_service
from openshift_assisted_service.models.operator_hardware_requirements import OperatorHardwareRequirements  # noqa: E501
from openshift_assisted_service.rest import ApiException

class TestOperatorHardwareRequirements(unittest.TestCase):
    """OperatorHardwareRequirements unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test OperatorHardwareRequirements
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OperatorHardwareRequirements`
        """
        model = openshift_assisted_service.models.operator_hardware_requirements.OperatorHardwareRequirements()  # noqa: E501
        if include_optional :
            return OperatorHardwareRequirements(
                operator_name = '', 
                dependencies = [
                    ''
                    ], 
                requirements = openshift_assisted_service.models.host_type_hardware_requirements_wrapper.host-type-hardware-requirements-wrapper(
                    worker = openshift_assisted_service.models.host_type_hardware_requirements.host-type-hardware-requirements(
                        quantitative = openshift_assisted_service.models.cluster_host_requirements_details.cluster-host-requirements-details(
                            cpu_cores = 56, 
                            ram_mib = 56, 
                            disk_size_gb = 56, 
                            installation_disk_speed_threshold_ms = 56, 
                            network_latency_threshold_ms = 1.337, 
                            packet_loss_percentage = 1.337, 
                            tpm_enabled_in_bios = True, ), 
                        qualitative = [
                            ''
                            ], ), 
                    master = openshift_assisted_service.models.host_type_hardware_requirements.host-type-hardware-requirements(), )
            )
        else :
            return OperatorHardwareRequirements(
        )
        """

    def testOperatorHardwareRequirements(self):
        """Test OperatorHardwareRequirements"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
