# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openshift_assisted_service
from openshift_assisted_service.models.disk_role import DiskRole  # noqa: E501
from openshift_assisted_service.rest import ApiException

class TestDiskRole(unittest.TestCase):
    """DiskRole unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDiskRole(self):
        """Test DiskRole"""
        # inst = DiskRole()

if __name__ == '__main__':
    unittest.main()
