# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openshift_assisted_service
from openshift_assisted_service.models.drive_type import DriveType  # noqa: E501
from openshift_assisted_service.rest import ApiException

class TestDriveType(unittest.TestCase):
    """DriveType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDriveType(self):
        """Test DriveType"""
        # inst = DriveType()

if __name__ == '__main__':
    unittest.main()
