# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openshift_assisted_service
from openshift_assisted_service.models.logs_state import LogsState  # noqa: E501
from openshift_assisted_service.rest import ApiException

class TestLogsState(unittest.TestCase):
    """LogsState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLogsState(self):
        """Test LogsState"""
        # inst = LogsState()

if __name__ == '__main__':
    unittest.main()
