# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openshift_assisted_service
from openshift_assisted_service.models.operator_status import OperatorStatus  # noqa: E501
from openshift_assisted_service.rest import ApiException

class TestOperatorStatus(unittest.TestCase):
    """OperatorStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOperatorStatus(self):
        """Test OperatorStatus"""
        # inst = OperatorStatus()

if __name__ == '__main__':
    unittest.main()
