# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openshift_assisted_service
from openshift_assisted_service.models.disk_encryption import DiskEncryption  # noqa: E501
from openshift_assisted_service.rest import ApiException

class TestDiskEncryption(unittest.TestCase):
    """DiskEncryption unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DiskEncryption
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DiskEncryption`
        """
        model = openshift_assisted_service.models.disk_encryption.DiskEncryption()  # noqa: E501
        if include_optional :
            return DiskEncryption(
                enable_on = 'none', 
                mode = 'tpmv2', 
                tang_servers = '[{"url":"http://tang.example.com:7500","thumbprint":"PLjNyRdGw03zlRoGjQYMahSZGu9"}, {"url":"http://tang.example.com:7501","thumbprint":"PLjNyRdGw03zlRoGjQYMahSZGu8"}]'
            )
        else :
            return DiskEncryption(
        )
        """

    def testDiskEncryption(self):
        """Test DiskEncryption"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
