# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openshift_assisted_service
from openshift_assisted_service.models.bind_host_params import BindHostParams  # noqa: E501
from openshift_assisted_service.rest import ApiException

class TestBindHostParams(unittest.TestCase):
    """BindHostParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BindHostParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `BindHostParams`
        """
        model = openshift_assisted_service.models.bind_host_params.BindHostParams()  # noqa: E501
        if include_optional :
            return BindHostParams(
                cluster_id = ''
            )
        else :
            return BindHostParams(
                cluster_id = '',
        )
        """

    def testBindHostParams(self):
        """Test BindHostParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
