# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openshift_assisted_service
from openshift_assisted_service.models.image_create_params import ImageCreateParams  # noqa: E501
from openshift_assisted_service.rest import ApiException

class TestImageCreateParams(unittest.TestCase):
    """ImageCreateParams unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ImageCreateParams
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ImageCreateParams`
        """
        model = openshift_assisted_service.models.image_create_params.ImageCreateParams()  # noqa: E501
        if include_optional :
            return ImageCreateParams(
                ssh_public_key = '', 
                static_network_config = [
                    openshift_assisted_service.models.host_static_network_config.host_static_network_config(
                        network_yaml = '', 
                        mac_interface_map = [
                            openshift_assisted_service.models.mac_interface_map_inner.mac_interface_map_inner(
                                mac_address = '62:CB:20:42:30:c0', 
                                logical_nic_name = '', )
                            ], )
                    ], 
                image_type = 'full-iso'
            )
        else :
            return ImageCreateParams(
        )
        """

    def testImageCreateParams(self):
        """Test ImageCreateParams"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
