# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import unittest
import datetime

import openshift_assisted_service
from openshift_assisted_service.models.disk_info import DiskInfo  # noqa: E501
from openshift_assisted_service.rest import ApiException

class TestDiskInfo(unittest.TestCase):
    """DiskInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DiskInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DiskInfo`
        """
        model = openshift_assisted_service.models.disk_info.DiskInfo()  # noqa: E501
        if include_optional :
            return DiskInfo(
                id = '', 
                path = '', 
                disk_speed = openshift_assisted_service.models.disk_speed.disk_speed(
                    tested = True, 
                    exit_code = 56, 
                    speed_ms = 56, )
            )
        else :
            return DiskInfo(
        )
        """

    def testDiskInfo(self):
        """Test DiskInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
