# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictInt

class ClusterProgressInfo(BaseModel):
    """
    ClusterProgressInfo
    """
    total_percentage: Optional[StrictInt] = None
    preparing_for_installation_stage_percentage: Optional[StrictInt] = None
    installing_stage_percentage: Optional[StrictInt] = None
    finalizing_stage_percentage: Optional[StrictInt] = None
    __properties = ["total_percentage", "preparing_for_installation_stage_percentage", "installing_stage_percentage", "finalizing_stage_percentage"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ClusterProgressInfo:
        """Create an instance of ClusterProgressInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ClusterProgressInfo:
        """Create an instance of ClusterProgressInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ClusterProgressInfo.parse_obj(obj)

        _obj = ClusterProgressInfo.parse_obj({
            "total_percentage": obj.get("total_percentage"),
            "preparing_for_installation_stage_percentage": obj.get("preparing_for_installation_stage_percentage"),
            "installing_stage_percentage": obj.get("installing_stage_percentage"),
            "finalizing_stage_percentage": obj.get("finalizing_stage_percentage")
        })
        return _obj


