# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, StrictStr, conlist
from openshift_assisted_service.models.connectivity_check_nic import ConnectivityCheckNic

class ConnectivityCheckHost(BaseModel):
    """
    ConnectivityCheckHost
    """
    host_id: Optional[StrictStr] = None
    nics: Optional[conlist(ConnectivityCheckNic)] = None
    __properties = ["host_id", "nics"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ConnectivityCheckHost:
        """Create an instance of ConnectivityCheckHost from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in nics (list)
        _items = []
        if self.nics:
            for _item in self.nics:
                if _item:
                    _items.append(_item.to_dict())
            _dict['nics'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ConnectivityCheckHost:
        """Create an instance of ConnectivityCheckHost from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ConnectivityCheckHost.parse_obj(obj)

        _obj = ConnectivityCheckHost.parse_obj({
            "host_id": obj.get("host_id"),
            "nics": [ConnectivityCheckNic.from_dict(_item) for _item in obj.get("nics")] if obj.get("nics") is not None else None
        })
        return _obj


