# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional, Union
from pydantic import BaseModel, StrictFloat, StrictInt, StrictStr, conlist

class Cpu(BaseModel):
    """
    Cpu
    """
    count: Optional[StrictInt] = None
    frequency: Optional[Union[StrictFloat, StrictInt]] = None
    flags: Optional[conlist(StrictStr)] = None
    model_name: Optional[StrictStr] = None
    architecture: Optional[StrictStr] = None
    __properties = ["count", "frequency", "flags", "model_name", "architecture"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Cpu:
        """Create an instance of Cpu from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Cpu:
        """Create an instance of Cpu from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Cpu.parse_obj(obj)

        _obj = Cpu.parse_obj({
            "count": obj.get("count"),
            "frequency": obj.get("frequency"),
            "flags": obj.get("flags"),
            "model_name": obj.get("model_name"),
            "architecture": obj.get("architecture")
        })
        return _obj


