# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr, constr, validator

class CreateManifestParams(BaseModel):
    """
    CreateManifestParams
    """
    folder: Optional[StrictStr] = Field('manifests', description="The folder that contains the files. Manifests can be placed in 'manifests' or 'openshift' directories.")
    file_name: constr(strict=True) = Field(..., description="The name of the manifest to customize the installed OCP cluster.")
    content: StrictStr = Field(..., description="base64 encoded manifest content.")
    __properties = ["folder", "file_name", "content"]

    @validator('folder')
    def folder_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in ('manifests', 'openshift'):
            raise ValueError("must be one of enum values ('manifests', 'openshift')")
        return value

    @validator('file_name')
    def file_name_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^[^\/]*\.(yaml|yml|json)$", value):
            raise ValueError(r"must validate the regular expression /^[^\/]*\.(yaml|yml|json)$/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CreateManifestParams:
        """Create an instance of CreateManifestParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CreateManifestParams:
        """Create an instance of CreateManifestParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CreateManifestParams.parse_obj(obj)

        _obj = CreateManifestParams.parse_obj({
            "folder": obj.get("folder") if obj.get("folder") is not None else 'manifests',
            "file_name": obj.get("file_name"),
            "content": obj.get("content")
        })
        return _obj


