# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, conlist

class DiskInstallationEligibility(BaseModel):
    """
    DiskInstallationEligibility
    """
    eligible: Optional[StrictBool] = Field(None, description="Whether the disk is eligible for installation or not.")
    not_eligible_reasons: Optional[conlist(StrictStr)] = Field(None, description="Reasons for why this disk is not eligible for installation.")
    __properties = ["eligible", "not_eligible_reasons"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DiskInstallationEligibility:
        """Create an instance of DiskInstallationEligibility from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DiskInstallationEligibility:
        """Create an instance of DiskInstallationEligibility from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DiskInstallationEligibility.parse_obj(obj)

        _obj = DiskInstallationEligibility.parse_obj({
            "eligible": obj.get("eligible"),
            "not_eligible_reasons": obj.get("not_eligible_reasons")
        })
        return _obj


