# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictStr
from openshift_assisted_service.models.disk_speed import DiskSpeed

class DiskInfo(BaseModel):
    """
    DiskInfo
    """
    id: Optional[StrictStr] = None
    path: Optional[StrictStr] = None
    disk_speed: Optional[DiskSpeed] = None
    __properties = ["id", "path", "disk_speed"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DiskInfo:
        """Create an instance of DiskInfo from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of disk_speed
        if self.disk_speed:
            _dict['disk_speed'] = self.disk_speed.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DiskInfo:
        """Create an instance of DiskInfo from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DiskInfo.parse_obj(obj)

        _obj = DiskInfo.parse_obj({
            "id": obj.get("id"),
            "path": obj.get("path"),
            "disk_speed": DiskSpeed.from_dict(obj.get("disk_speed")) if obj.get("disk_speed") is not None else None
        })
        return _obj


