# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, conlist
from openshift_assisted_service.models.domain_resolution_response_resolutions_inner import DomainResolutionResponseResolutionsInner

class DomainResolutionResponse(BaseModel):
    """
    DomainResolutionResponse
    """
    resolutions: conlist(DomainResolutionResponseResolutionsInner) = Field(...)
    __properties = ["resolutions"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> DomainResolutionResponse:
        """Create an instance of DomainResolutionResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in resolutions (list)
        _items = []
        if self.resolutions:
            for _item in self.resolutions:
                if _item:
                    _items.append(_item.to_dict())
            _dict['resolutions'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> DomainResolutionResponse:
        """Create an instance of DomainResolutionResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return DomainResolutionResponse.parse_obj(obj)

        _obj = DomainResolutionResponse.parse_obj({
            "resolutions": [DomainResolutionResponseResolutionsInner.from_dict(_item) for _item in obj.get("resolutions")] if obj.get("resolutions") is not None else None
        })
        return _obj


