# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class DriveType(str, Enum):
    """
    DriveType
    """

    """
    allowed enum values
    """
    UNKNOWN = 'Unknown'
    HDD = 'HDD'
    FDD = 'FDD'
    ODD = 'ODD'
    SSD = 'SSD'
    VIRTUAL = 'virtual'
    MULTIPATH = 'Multipath'
    ISCSI = 'iSCSI'
    FC = 'FC'
    LVM = 'LVM'
    RAID = 'RAID'
    ECKD = 'ECKD'
    ECKD_LEFT_PARENTHESIS_ESE_RIGHT_PARENTHESIS = 'ECKD (ESE)'
    FBA = 'FBA'

    @classmethod
    def from_json(cls, json_str: str) -> DriveType:
        """Create an instance of DriveType from a JSON string"""
        return DriveType(json.loads(json_str))


