# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class FeatureSupportLevelId(str, Enum):
    """
    FeatureSupportLevelId
    """

    """
    allowed enum values
    """
    SNO = 'SNO'
    VIP_AUTO_ALLOC = 'VIP_AUTO_ALLOC'
    CUSTOM_MANIFEST = 'CUSTOM_MANIFEST'
    SINGLE_NODE_EXPANSION = 'SINGLE_NODE_EXPANSION'
    LVM = 'LVM'
    ODF = 'ODF'
    LSO = 'LSO'
    CNV = 'CNV'
    MCE = 'MCE'
    NUTANIX_INTEGRATION = 'NUTANIX_INTEGRATION'
    VSPHERE_INTEGRATION = 'VSPHERE_INTEGRATION'
    DUAL_STACK_VIPS = 'DUAL_STACK_VIPS'
    CLUSTER_MANAGED_NETWORKING = 'CLUSTER_MANAGED_NETWORKING'
    USER_MANAGED_NETWORKING = 'USER_MANAGED_NETWORKING'
    MINIMAL_ISO = 'MINIMAL_ISO'
    FULL_ISO = 'FULL_ISO'
    EXTERNAL_PLATFORM_OCI = 'EXTERNAL_PLATFORM_OCI'
    DUAL_STACK = 'DUAL_STACK'

    @classmethod
    def from_json(cls, json_str: str) -> FeatureSupportLevelId:
        """Create an instance of FeatureSupportLevelId from a JSON string"""
        return FeatureSupportLevelId(json.loads(json_str))


