# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist
from openshift_assisted_service.models.feature_support_level_features_inner import FeatureSupportLevelFeaturesInner

class FeatureSupportLevel(BaseModel):
    """
    (DEPRECATED) List of features attached to openshift version
    """
    openshift_version: Optional[StrictStr] = Field(None, description="Version of the OpenShift cluster.")
    features: Optional[conlist(FeatureSupportLevelFeaturesInner)] = None
    __properties = ["openshift_version", "features"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> FeatureSupportLevel:
        """Create an instance of FeatureSupportLevel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in features (list)
        _items = []
        if self.features:
            for _item in self.features:
                if _item:
                    _items.append(_item.to_dict())
            _dict['features'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> FeatureSupportLevel:
        """Create an instance of FeatureSupportLevel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return FeatureSupportLevel.parse_obj(obj)

        _obj = FeatureSupportLevel.parse_obj({
            "openshift_version": obj.get("openshift_version"),
            "features": [FeatureSupportLevelFeaturesInner.from_dict(_item) for _item in obj.get("features")] if obj.get("features") is not None else None
        })
        return _obj


