# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class HostStage(str, Enum):
    """
    HostStage
    """

    """
    allowed enum values
    """
    STARTING_INSTALLATION = 'Starting installation'
    WAITING_FOR_CONTROL_PLANE = 'Waiting for control plane'
    WAITING_FOR_BOOTKUBE = 'Waiting for bootkube'
    WAITING_FOR_CONTROLLER = 'Waiting for controller'
    INSTALLING = 'Installing'
    WRITING_IMAGE_TO_DISK = 'Writing image to disk'
    REBOOTING = 'Rebooting'
    WAITING_FOR_IGNITION = 'Waiting for ignition'
    CONFIGURING = 'Configuring'
    JOINED = 'Joined'
    DONE = 'Done'
    FAILED = 'Failed'

    @classmethod
    def from_json(cls, json_str: str) -> HostStage:
        """Create an instance of HostStage from a JSON string"""
        return HostStage(json.loads(json_str))


