# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class HostRoleUpdateParams(str, Enum):
    """
    HostRoleUpdateParams
    """

    """
    allowed enum values
    """
    AUTO_MINUS_ASSIGN = 'auto-assign'
    MASTER = 'master'
    WORKER = 'worker'

    @classmethod
    def from_json(cls, json_str: str) -> HostRoleUpdateParams:
        """Create an instance of HostRoleUpdateParams from a JSON string"""
        return HostRoleUpdateParams(json.loads(json_str))


