# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class HostValidationId(str, Enum):
    """
    HostValidationId
    """

    """
    allowed enum values
    """
    CONNECTED = 'connected'
    MEDIA_MINUS_CONNECTED = 'media-connected'
    HAS_MINUS_INVENTORY = 'has-inventory'
    HAS_MINUS_MIN_MINUS_CPU_MINUS_CORES = 'has-min-cpu-cores'
    HAS_MINUS_MIN_MINUS_VALID_MINUS_DISKS = 'has-min-valid-disks'
    HAS_MINUS_MIN_MINUS_MEMORY = 'has-min-memory'
    MACHINE_MINUS_CIDR_MINUS_DEFINED = 'machine-cidr-defined'
    HAS_MINUS_CPU_MINUS_CORES_MINUS_FOR_MINUS_ROLE = 'has-cpu-cores-for-role'
    HAS_MINUS_MEMORY_MINUS_FOR_MINUS_ROLE = 'has-memory-for-role'
    HOSTNAME_MINUS_UNIQUE = 'hostname-unique'
    HOSTNAME_MINUS_VALID = 'hostname-valid'
    BELONGS_MINUS_TO_MINUS_MACHINE_MINUS_CIDR = 'belongs-to-machine-cidr'
    IGNITION_MINUS_DOWNLOADABLE = 'ignition-downloadable'
    BELONGS_MINUS_TO_MINUS_MAJORITY_MINUS_GROUP = 'belongs-to-majority-group'
    VALID_MINUS_PLATFORM_MINUS_NETWORK_MINUS_SETTINGS = 'valid-platform-network-settings'
    NTP_MINUS_SYNCED = 'ntp-synced'
    TIME_MINUS_SYNCED_MINUS_BETWEEN_MINUS_HOST_MINUS_AND_MINUS_SERVICE = 'time-synced-between-host-and-service'
    CONTAINER_MINUS_IMAGES_MINUS_AVAILABLE = 'container-images-available'
    LSO_MINUS_REQUIREMENTS_MINUS_SATISFIED = 'lso-requirements-satisfied'
    OCS_MINUS_REQUIREMENTS_MINUS_SATISFIED = 'ocs-requirements-satisfied'
    ODF_MINUS_REQUIREMENTS_MINUS_SATISFIED = 'odf-requirements-satisfied'
    LVM_MINUS_REQUIREMENTS_MINUS_SATISFIED = 'lvm-requirements-satisfied'
    MCE_MINUS_REQUIREMENTS_MINUS_SATISFIED = 'mce-requirements-satisfied'
    SUFFICIENT_MINUS_INSTALLATION_MINUS_DISK_MINUS_SPEED = 'sufficient-installation-disk-speed'
    CNV_MINUS_REQUIREMENTS_MINUS_SATISFIED = 'cnv-requirements-satisfied'
    SUFFICIENT_MINUS_NETWORK_MINUS_LATENCY_MINUS_REQUIREMENT_MINUS_FOR_MINUS_ROLE = 'sufficient-network-latency-requirement-for-role'
    SUFFICIENT_MINUS_PACKET_MINUS_LOSS_MINUS_REQUIREMENT_MINUS_FOR_MINUS_ROLE = 'sufficient-packet-loss-requirement-for-role'
    HAS_MINUS_DEFAULT_MINUS_ROUTE = 'has-default-route'
    API_MINUS_DOMAIN_MINUS_NAME_MINUS_RESOLVED_MINUS_CORRECTLY = 'api-domain-name-resolved-correctly'
    API_MINUS_INT_MINUS_DOMAIN_MINUS_NAME_MINUS_RESOLVED_MINUS_CORRECTLY = 'api-int-domain-name-resolved-correctly'
    APPS_MINUS_DOMAIN_MINUS_NAME_MINUS_RESOLVED_MINUS_CORRECTLY = 'apps-domain-name-resolved-correctly'
    RELEASE_MINUS_DOMAIN_MINUS_NAME_MINUS_RESOLVED_MINUS_CORRECTLY = 'release-domain-name-resolved-correctly'
    COMPATIBLE_MINUS_WITH_MINUS_CLUSTER_MINUS_PLATFORM = 'compatible-with-cluster-platform'
    DNS_MINUS_WILDCARD_MINUS_NOT_MINUS_CONFIGURED = 'dns-wildcard-not-configured'
    DISK_MINUS_ENCRYPTION_MINUS_REQUIREMENTS_MINUS_SATISFIED = 'disk-encryption-requirements-satisfied'
    NON_MINUS_OVERLAPPING_MINUS_SUBNETS = 'non-overlapping-subnets'
    VSPHERE_MINUS_DISK_MINUS_UUID_MINUS_ENABLED = 'vsphere-disk-uuid-enabled'
    COMPATIBLE_MINUS_AGENT = 'compatible-agent'
    NO_MINUS_SKIP_MINUS_INSTALLATION_MINUS_DISK = 'no-skip-installation-disk'
    NO_MINUS_SKIP_MINUS_MISSING_MINUS_DISK = 'no-skip-missing-disk'
    NO_MINUS_IP_MINUS_COLLISIONS_MINUS_IN_MINUS_NETWORK = 'no-ip-collisions-in-network'

    @classmethod
    def from_json(cls, json_str: str) -> HostValidationId:
        """Create an instance of HostValidationId from a JSON string"""
        return HostValidationId(json.loads(json_str))


