# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class ImageType(str, Enum):
    """
    ImageType
    """

    """
    allowed enum values
    """
    FULL_MINUS_ISO = 'full-iso'
    MINIMAL_MINUS_ISO = 'minimal-iso'

    @classmethod
    def from_json(cls, json_str: str) -> ImageType:
        """Create an instance of ImageType from a JSON string"""
        return ImageType(json.loads(json_str))


