# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class ImportClusterParams(BaseModel):
    """
    ImportClusterParams
    """
    name: StrictStr = Field(..., description="OpenShift cluster name.")
    api_vip_dnsname: StrictStr = Field(..., description="The domain name used to reach the OpenShift cluster API.")
    openshift_version: Optional[StrictStr] = Field(None, description="Version of the OpenShift cluster.")
    openshift_cluster_id: StrictStr = Field(..., description="The id of the OCP cluster, that hosts will be added to")
    __properties = ["name", "api_vip_dnsname", "openshift_version", "openshift_cluster_id"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ImportClusterParams:
        """Create an instance of ImportClusterParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ImportClusterParams:
        """Create an instance of ImportClusterParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ImportClusterParams.parse_obj(obj)

        _obj = ImportClusterParams.parse_obj({
            "name": obj.get("name"),
            "api_vip_dnsname": obj.get("api_vip_dnsname"),
            "openshift_version": obj.get("openshift_version"),
            "openshift_cluster_id": obj.get("openshift_cluster_id")
        })
        return _obj


