# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class LogsState(str, Enum):
    """
    LogsState
    """

    """
    allowed enum values
    """
    REQUESTED = 'requested'
    COLLECTING = 'collecting'
    COMPLETED = 'completed'
    TIMEOUT = 'timeout'
    EMPTY = ''

    @classmethod
    def from_json(cls, json_str: str) -> LogsState:
        """Create an instance of LogsState from a JSON string"""
        return LogsState(json.loads(json_str))


