# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class MemoryMethod(str, Enum):
    """
    MemoryMethod
    """

    """
    allowed enum values
    """
    DMIDECODE = 'dmidecode'
    GHW = 'ghw'
    MEMINFO = 'meminfo'

    @classmethod
    def from_json(cls, json_str: str) -> MemoryMethod:
        """Create an instance of MemoryMethod from a JSON string"""
        return MemoryMethod(json.loads(json_str))


