# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictInt
from openshift_assisted_service.models.memory_method import MemoryMethod

class Memory(BaseModel):
    """
    Memory
    """
    physical_bytes: Optional[StrictInt] = None
    usable_bytes: Optional[StrictInt] = None
    physical_bytes_method: Optional[MemoryMethod] = None
    __properties = ["physical_bytes", "usable_bytes", "physical_bytes_method"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Memory:
        """Create an instance of Memory from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Memory:
        """Create an instance of Memory from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Memory.parse_obj(obj)

        _obj = Memory.parse_obj({
            "physical_bytes": obj.get("physical_bytes"),
            "usable_bytes": obj.get("usable_bytes"),
            "physical_bytes_method": obj.get("physical_bytes_method")
        })
        return _obj


