# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json



from pydantic import BaseModel, Field, StrictStr, constr, validator

class NextStepCmdRequest(BaseModel):
    """
    NextStepCmdRequest
    """
    infra_env_id: StrictStr = Field(..., description="Infra env id")
    host_id: StrictStr = Field(..., description="Host id")
    agent_version: constr(strict=True) = Field(..., description="Agent image version")
    __properties = ["infra_env_id", "host_id", "agent_version"]

    @validator('agent_version')
    def agent_version_validate_regular_expression(cls, value):
        """Validates the regular expression"""
        if not re.match(r"^(([a-zA-Z0-9\-\.]+)(:[0-9]+)?\/)?[a-z0-9\._\-\/@]+[?::a-zA-Z0-9_\-.]+$", value):
            raise ValueError(r"must validate the regular expression /^(([a-zA-Z0-9\-\.]+)(:[0-9]+)?\/)?[a-z0-9\._\-\/@]+[?::a-zA-Z0-9_\-.]+$/")
        return value

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> NextStepCmdRequest:
        """Create an instance of NextStepCmdRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> NextStepCmdRequest:
        """Create an instance of NextStepCmdRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return NextStepCmdRequest.parse_obj(obj)

        _obj = NextStepCmdRequest.parse_obj({
            "infra_env_id": obj.get("infra_env_id"),
            "host_id": obj.get("host_id"),
            "agent_version": obj.get("agent_version")
        })
        return _obj


