# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist
from openshift_assisted_service.models.host_type_hardware_requirements_wrapper import HostTypeHardwareRequirementsWrapper

class OperatorHardwareRequirements(BaseModel):
    """
    OperatorHardwareRequirements
    """
    operator_name: Optional[StrictStr] = Field(None, description="Unique name of the operator. Corresponds to name property of the monitored-operator, i.e. \"lso\", \"cnv\", etc.")
    dependencies: Optional[conlist(StrictStr)] = Field(None, description="List of other operator unique names that are required to be installed. Corresponds to name property of the monitored-operator, i.e. \"lso\", \"cnv\", etc.")
    requirements: Optional[HostTypeHardwareRequirementsWrapper] = None
    __properties = ["operator_name", "dependencies", "requirements"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> OperatorHardwareRequirements:
        """Create an instance of OperatorHardwareRequirements from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of requirements
        if self.requirements:
            _dict['requirements'] = self.requirements.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> OperatorHardwareRequirements:
        """Create an instance of OperatorHardwareRequirements from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return OperatorHardwareRequirements.parse_obj(obj)

        _obj = OperatorHardwareRequirements.parse_obj({
            "operator_name": obj.get("operator_name"),
            "dependencies": obj.get("dependencies"),
            "requirements": HostTypeHardwareRequirementsWrapper.from_dict(obj.get("requirements")) if obj.get("requirements") is not None else None
        })
        return _obj


