# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class OperatorCreateParams(BaseModel):
    """
    OperatorCreateParams
    """
    name: Optional[StrictStr] = None
    properties: Optional[StrictStr] = Field(None, description="Blob of operator-dependent parameters that are required for installation.")
    __properties = ["name", "properties"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> OperatorCreateParams:
        """Create an instance of OperatorCreateParams from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> OperatorCreateParams:
        """Create an instance of OperatorCreateParams from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return OperatorCreateParams.parse_obj(obj)

        _obj = OperatorCreateParams.parse_obj({
            "name": obj.get("name"),
            "properties": obj.get("properties")
        })
        return _obj


