# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class PlatformType(str, Enum):
    """
    PlatformType
    """

    """
    allowed enum values
    """
    BAREMETAL = 'baremetal'
    NUTANIX = 'nutanix'
    VSPHERE = 'vsphere'
    NONE = 'none'
    OCI = 'oci'

    @classmethod
    def from_json(cls, json_str: str) -> PlatformType:
        """Create an instance of PlatformType from a JSON string"""
        return PlatformType(json.loads(json_str))


