# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool
from openshift_assisted_service.models.platform_type import PlatformType

class Platform(BaseModel):
    """
    The configuration for the specific platform upon which to perform the installation.
    """
    type: PlatformType = Field(...)
    is_external: Optional[StrictBool] = Field(None, description="Used by the service to indicate that the platform-specific components are not included in OpenShift and must be provided as manifests separately.")
    __properties = ["type", "is_external"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Platform:
        """Create an instance of Platform from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                            "is_external",
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Platform:
        """Create an instance of Platform from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Platform.parse_obj(obj)

        _obj = Platform.parse_obj({
            "type": obj.get("type"),
            "is_external": obj.get("is_external")
        })
        return _obj


