# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictStr

class PresignedUrl(BaseModel):
    """
    PresignedUrl
    """
    url: StrictStr = Field(..., description="Pre-signed URL for downloading the infra-env discovery image.")
    expires_at: Optional[datetime] = Field(None, description="Expiration time for the URL token.")
    __properties = ["url", "expires_at"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PresignedUrl:
        """Create an instance of PresignedUrl from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PresignedUrl:
        """Create an instance of PresignedUrl from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PresignedUrl.parse_obj(obj)

        _obj = PresignedUrl.parse_obj({
            "url": obj.get("url"),
            "expires_at": obj.get("expires_at")
        })
        return _obj


