# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class SourceState(str, Enum):
    """
    SourceState
    """

    """
    allowed enum values
    """
    SYNCED = 'synced'
    COMBINED = 'combined'
    NOT_COMBINED = 'not_combined'
    ERROR = 'error'
    VARIABLE = 'variable'
    UNREACHABLE = 'unreachable'

    @classmethod
    def from_json(cls, json_str: str) -> SourceState:
        """Create an instance of SourceState from a JSON string"""
        return SourceState(json.loads(json_str))


