# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class StepType(str, Enum):
    """
    StepType
    """

    """
    allowed enum values
    """
    CONNECTIVITY_MINUS_CHECK = 'connectivity-check'
    EXECUTE = 'execute'
    INVENTORY = 'inventory'
    INSTALL = 'install'
    FREE_MINUS_NETWORK_MINUS_ADDRESSES = 'free-network-addresses'
    DHCP_MINUS_LEASE_MINUS_ALLOCATE = 'dhcp-lease-allocate'
    API_MINUS_VIP_MINUS_CONNECTIVITY_MINUS_CHECK = 'api-vip-connectivity-check'
    TANG_MINUS_CONNECTIVITY_MINUS_CHECK = 'tang-connectivity-check'
    NTP_MINUS_SYNCHRONIZER = 'ntp-synchronizer'
    INSTALLATION_MINUS_DISK_MINUS_SPEED_MINUS_CHECK = 'installation-disk-speed-check'
    CONTAINER_MINUS_IMAGE_MINUS_AVAILABILITY = 'container-image-availability'
    DOMAIN_MINUS_RESOLUTION = 'domain-resolution'
    STOP_MINUS_INSTALLATION = 'stop-installation'
    LOGS_MINUS_GATHER = 'logs-gather'
    NEXT_MINUS_STEP_MINUS_RUNNER = 'next-step-runner'
    UPGRADE_MINUS_AGENT = 'upgrade-agent'
    DOWNLOAD_MINUS_BOOT_MINUS_ARTIFACTS = 'download-boot-artifacts'
    REBOOT_MINUS_FOR_MINUS_RECLAIM = 'reboot-for-reclaim'
    VERIFY_MINUS_VIPS = 'verify-vips'

    @classmethod
    def from_json(cls, json_str: str) -> StepType:
        """Create an instance of StepType from a JSON string"""
        return StepType(json.loads(json_str))


