# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, StrictInt, StrictStr
from openshift_assisted_service.models.step_type import StepType

class StepReply(BaseModel):
    """
    StepReply
    """
    step_type: Optional[StepType] = None
    step_id: Optional[StrictStr] = None
    exit_code: Optional[StrictInt] = None
    output: Optional[StrictStr] = None
    error: Optional[StrictStr] = None
    __properties = ["step_type", "step_id", "exit_code", "output", "error"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> StepReply:
        """Create an instance of StepReply from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> StepReply:
        """Create an instance of StepReply from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return StepReply.parse_obj(obj)

        _obj = StepReply.parse_obj({
            "step_type": obj.get("step_type"),
            "step_id": obj.get("step_id"),
            "exit_code": obj.get("exit_code"),
            "output": obj.get("output"),
            "error": obj.get("error")
        })
        return _obj


