# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class SupportLevel(str, Enum):
    """
    SupportLevel
    """

    """
    allowed enum values
    """
    SUPPORTED = 'supported'
    UNSUPPORTED = 'unsupported'
    TECH_MINUS_PREVIEW = 'tech-preview'
    DEV_MINUS_PREVIEW = 'dev-preview'
    UNAVAILABLE = 'unavailable'

    @classmethod
    def from_json(cls, json_str: str) -> SupportLevel:
        """Create an instance of SupportLevel from a JSON string"""
        return SupportLevel(json.loads(json_str))


