# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr

class SystemVendor(BaseModel):
    """
    SystemVendor
    """
    serial_number: Optional[StrictStr] = None
    product_name: Optional[StrictStr] = None
    manufacturer: Optional[StrictStr] = None
    virtual: Optional[StrictBool] = Field(None, description="Whether the machine appears to be a virtual machine or not")
    __properties = ["serial_number", "product_name", "manufacturer", "virtual"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SystemVendor:
        """Create an instance of SystemVendor from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SystemVendor:
        """Create an instance of SystemVendor from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SystemVendor.parse_obj(obj)

        _obj = SystemVendor.parse_obj({
            "serial_number": obj.get("serial_number"),
            "product_name": obj.get("product_name"),
            "manufacturer": obj.get("manufacturer"),
            "virtual": obj.get("virtual")
        })
        return _obj


