# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist
from openshift_assisted_service.models.tang_connectivity_response_tang_server_response_inner_signatures_inner import TangConnectivityResponseTangServerResponseInnerSignaturesInner

class TangConnectivityResponseTangServerResponseInner(BaseModel):
    """
    TangConnectivityResponseTangServerResponseInner
    """
    tang_url: Optional[StrictStr] = Field(None, description="Tang URL.")
    payload: Optional[StrictStr] = Field(None, description="Tang response payload.")
    signatures: Optional[conlist(TangConnectivityResponseTangServerResponseInnerSignaturesInner)] = None
    __properties = ["tang_url", "payload", "signatures"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TangConnectivityResponseTangServerResponseInner:
        """Create an instance of TangConnectivityResponseTangServerResponseInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in signatures (list)
        _items = []
        if self.signatures:
            for _item in self.signatures:
                if _item:
                    _items.append(_item.to_dict())
            _dict['signatures'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TangConnectivityResponseTangServerResponseInner:
        """Create an instance of TangConnectivityResponseTangServerResponseInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TangConnectivityResponseTangServerResponseInner.parse_obj(obj)

        _obj = TangConnectivityResponseTangServerResponseInner.parse_obj({
            "tang_url": obj.get("tang_url"),
            "payload": obj.get("payload"),
            "signatures": [TangConnectivityResponseTangServerResponseInnerSignaturesInner.from_dict(_item) for _item in obj.get("signatures")] if obj.get("signatures") is not None else None
        })
        return _obj


