# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class VipVerification(str, Enum):
    """
    vip verification result.
    """

    """
    allowed enum values
    """
    UNVERIFIED = 'unverified'
    FAILED = 'failed'
    SUCCEEDED = 'succeeded'

    @classmethod
    def from_json(cls, json_str: str) -> VipVerification:
        """Create an instance of VipVerification from a JSON string"""
        return VipVerification(json.loads(json_str))


