# coding: utf-8

"""
    AssistedInstall

    Assisted installation  # noqa: E501

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg





class VipType(str, Enum):
    """
    The vip type.
    """

    """
    allowed enum values
    """
    API = 'api'
    INGRESS = 'ingress'

    @classmethod
    def from_json(cls, json_str: str) -> VipType:
        """Create an instance of VipType from a JSON string"""
        return VipType(json.loads(json_str))


